<?php



namespace Plugin\CustomShipping\Repository;

use Plugin\CustomShipping\Entity\CusShipping;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;


/**
 * CusShippingRepository
 * 
 * This class was generated by Doctrine ORM
 */


class CusShippingRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, CusShipping::class);
    }
}
