<?php



namespace Customize\Repository;

use Customize\Entity\Holiday;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Doctrine\ORM\Query\Expr\Join;


/**
 * HolidayRepository
 * 
 * This class was generated by Doctrine ORM
 */


class HolidayRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Holiday::class);
    }
    public function getHoliday_1_List(){
        $qb = $this->createQueryBuilder('h')->where('h.del_flag = 1');
        $List = $qb->getQuery()->getResult();
        $array = [];       
        foreach($List as $k => $item){
            $array[] = $item->getYear().'/'.$item->getMonth().'/'.$item->getDay();
        }
        
        // var_export($array);die;
        return $array;
    }
}
