<?php



namespace Customize\Repository;

use Customize\Entity\WeekHoliday;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;


/**
 * WeekHolidayRepository
 * 
 * This class was generated by Doctrine ORM
 */


class WeekHolidayRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, WeekHoliday::class);
    }
    public function getHoliday_week_List(){
        $qb = $this->createQueryBuilder('wh')->where('wh.status = 1');
        $List = $qb->getQuery()->getResult();
        $array = [];
        foreach($List as $item){
            $array[] = $item->getYobiId();
        }
        return $array;
    }
}
