<?php

/*
 * This file is part of PostCarrier for EC-CUBE
 *
 * Copyright(c) IPLOGIC CO.,LTD. All Rights Reserved.
 *
 * http://www.iplogic.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\PostCarrier4\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\PostCarrier4\Entity\PostCarrierConfig;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * PostCarrier Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCarrierConfigRepository extends AbstractRepository
{
    /**
     * PostCarrierConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, PostCarrierConfig::class);
    }

    /**
     * @param int $id
     *
     * @return null|PostCarrierConfig
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
